spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true
    locations: db/migration

  hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    ddl-auto: validate
    show-sql: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${MAIL_SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

myapp:
  secretKey: ${SECRET_KEY_JWT}
  validation: ${VALIDATION_JWT}

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    region:
      static: ${S3_REGION}
    stack:
      auto: false
application:
  bucket:
    name: ${S3_BUCKET_NAME}

google-client-key: ${GOOGLE_CLIENT_ID}

stripe-key: ${STRIPE_SECRET_KEY}

active-profile: ${DEFAULT_PROFILE_PICTURE}
